# Site settings
destination: ./_site
title: Margaret Meek Lange
email: margaret.meek@gmail.com
description: Exploring Data Science 
url: "http://margaretlange.github.io" # the base hostname & protocol for your site
twitter_username: ememell12345
github_username:  margaretlange

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

